dependencies:
  build:
   - maven:3.5.2
   - java:8.252.09
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn -B install -Papache-release -Dgpg.skip=true -Drat.numUnapprovedLicenses=100
ci:
  builds:
    - name: default
      build_target: default
