dependencies:
  build:
   - maven:3.6.3
   - java:11.0.8
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn -B test -Papache-release -Dgpg.skip=true -Drat.numUnapprovedLicenses=100
ci:
  builds:
    - name: default
      build_target: default
